// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pkg

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearWatchlistStmt, err = db.PrepareContext(ctx, clearWatchlist); err != nil {
		return nil, fmt.Errorf("error preparing query ClearWatchlist: %w", err)
	}
	if q.getSongByIdStmt, err = db.PrepareContext(ctx, getSongById); err != nil {
		return nil, fmt.Errorf("error preparing query GetSongById: %w", err)
	}
	if q.getUniqueSongsInWatchlistStmt, err = db.PrepareContext(ctx, getUniqueSongsInWatchlist); err != nil {
		return nil, fmt.Errorf("error preparing query GetUniqueSongsInWatchlist: %w", err)
	}
	if q.getUsersForSongIDStmt, err = db.PrepareContext(ctx, getUsersForSongID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsersForSongID: %w", err)
	}
	if q.getWatchListForUserStmt, err = db.PrepareContext(ctx, getWatchListForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetWatchListForUser: %w", err)
	}
	if q.insertSongStmt, err = db.PrepareContext(ctx, insertSong); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSong: %w", err)
	}
	if q.removeSongStmt, err = db.PrepareContext(ctx, removeSong); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveSong: %w", err)
	}
	if q.removeSongFromWatchlistStmt, err = db.PrepareContext(ctx, removeSongFromWatchlist); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveSongFromWatchlist: %w", err)
	}
	if q.setSongStreamableStmt, err = db.PrepareContext(ctx, setSongStreamable); err != nil {
		return nil, fmt.Errorf("error preparing query SetSongStreamable: %w", err)
	}
	if q.watchSongStmt, err = db.PrepareContext(ctx, watchSong); err != nil {
		return nil, fmt.Errorf("error preparing query WatchSong: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearWatchlistStmt != nil {
		if cerr := q.clearWatchlistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearWatchlistStmt: %w", cerr)
		}
	}
	if q.getSongByIdStmt != nil {
		if cerr := q.getSongByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSongByIdStmt: %w", cerr)
		}
	}
	if q.getUniqueSongsInWatchlistStmt != nil {
		if cerr := q.getUniqueSongsInWatchlistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUniqueSongsInWatchlistStmt: %w", cerr)
		}
	}
	if q.getUsersForSongIDStmt != nil {
		if cerr := q.getUsersForSongIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsersForSongIDStmt: %w", cerr)
		}
	}
	if q.getWatchListForUserStmt != nil {
		if cerr := q.getWatchListForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWatchListForUserStmt: %w", cerr)
		}
	}
	if q.insertSongStmt != nil {
		if cerr := q.insertSongStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSongStmt: %w", cerr)
		}
	}
	if q.removeSongStmt != nil {
		if cerr := q.removeSongStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeSongStmt: %w", cerr)
		}
	}
	if q.removeSongFromWatchlistStmt != nil {
		if cerr := q.removeSongFromWatchlistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeSongFromWatchlistStmt: %w", cerr)
		}
	}
	if q.setSongStreamableStmt != nil {
		if cerr := q.setSongStreamableStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSongStreamableStmt: %w", cerr)
		}
	}
	if q.watchSongStmt != nil {
		if cerr := q.watchSongStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing watchSongStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	clearWatchlistStmt            *sql.Stmt
	getSongByIdStmt               *sql.Stmt
	getUniqueSongsInWatchlistStmt *sql.Stmt
	getUsersForSongIDStmt         *sql.Stmt
	getWatchListForUserStmt       *sql.Stmt
	insertSongStmt                *sql.Stmt
	removeSongStmt                *sql.Stmt
	removeSongFromWatchlistStmt   *sql.Stmt
	setSongStreamableStmt         *sql.Stmt
	watchSongStmt                 *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		clearWatchlistStmt:            q.clearWatchlistStmt,
		getSongByIdStmt:               q.getSongByIdStmt,
		getUniqueSongsInWatchlistStmt: q.getUniqueSongsInWatchlistStmt,
		getUsersForSongIDStmt:         q.getUsersForSongIDStmt,
		getWatchListForUserStmt:       q.getWatchListForUserStmt,
		insertSongStmt:                q.insertSongStmt,
		removeSongStmt:                q.removeSongStmt,
		removeSongFromWatchlistStmt:   q.removeSongFromWatchlistStmt,
		setSongStreamableStmt:         q.setSongStreamableStmt,
		watchSongStmt:                 q.watchSongStmt,
	}
}
