// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pkg

import (
	"time"
)

type Song struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Artists      string    `json:"artists"`
	Duration     int64     `json:"duration"`
	RequestTime  time.Time `json:"request_time"`
	IsStreamable int64     `json:"is_streamable"`
	MessageID    string    `json:"message_id"`
}

type Watchlist struct {
	UserID string `json:"user_id"`
	SongID string `json:"song_id"`
}
