// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: songs.sql

package pkg

import (
	"context"
	"time"
)

const getSongById = `-- name: GetSongById :one
SELECT id, title, artists, duration, request_time, is_streamable FROM songs WHERE id = ?
`

func (q *Queries) GetSongById(ctx context.Context, id string) (Song, error) {
	row := q.queryRow(ctx, q.getSongByIdStmt, getSongById, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artists,
		&i.Duration,
		&i.RequestTime,
		&i.IsStreamable,
	)
	return i, err
}

const insertSong = `-- name: InsertSong :one
INSERT INTO songs (id, title, artists, duration, request_time, is_streamable) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, title, artists, duration, request_time, is_streamable
`

type InsertSongParams struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Artists      string    `json:"artists"`
	Duration     int64     `json:"duration"`
	RequestTime  time.Time `json:"request_time"`
	IsStreamable int64     `json:"is_streamable"`
}

func (q *Queries) InsertSong(ctx context.Context, arg InsertSongParams) (Song, error) {
	row := q.queryRow(ctx, q.insertSongStmt, insertSong,
		arg.ID,
		arg.Title,
		arg.Artists,
		arg.Duration,
		arg.RequestTime,
		arg.IsStreamable,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artists,
		&i.Duration,
		&i.RequestTime,
		&i.IsStreamable,
	)
	return i, err
}

const removeSong = `-- name: RemoveSong :exec
DELETE FROM songs WHERE id = ?
`

func (q *Queries) RemoveSong(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.removeSongStmt, removeSong, id)
	return err
}
