// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: watchlists.sql

package pkg

import (
	"context"
)

const clearWatchlist = `-- name: ClearWatchlist :exec
DELETE FROM watchlists WHERE user_id = ?
`

func (q *Queries) ClearWatchlist(ctx context.Context, userID string) error {
	_, err := q.exec(ctx, q.clearWatchlistStmt, clearWatchlist, userID)
	return err
}

const getUniqueSongsInWatchlist = `-- name: GetUniqueSongsInWatchlist :many
SELECT DISTINCT songs.id, songs.title, songs.artists, songs.duration, songs.request_time, songs.is_streamable FROM watchlists JOIN songs ON watchlists.song_id = songs.id
`

func (q *Queries) GetUniqueSongsInWatchlist(ctx context.Context) ([]Song, error) {
	rows, err := q.query(ctx, q.getUniqueSongsInWatchlistStmt, getUniqueSongsInWatchlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artists,
			&i.Duration,
			&i.RequestTime,
			&i.IsStreamable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchListForUser = `-- name: GetWatchListForUser :many
SELECT songs.id, songs.title, songs.artists, songs.duration, songs.request_time, songs.is_streamable FROM watchlists JOIN songs ON watchlists.song_id = songs.id WHERE watchlists.user_id = ?
`

func (q *Queries) GetWatchListForUser(ctx context.Context, userID string) ([]Song, error) {
	rows, err := q.query(ctx, q.getWatchListForUserStmt, getWatchListForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artists,
			&i.Duration,
			&i.RequestTime,
			&i.IsStreamable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromWatchlist = `-- name: RemoveSongFromWatchlist :exec
DELETE FROM watchlists WHERE song_id = ? AND user_id = ?
`

type RemoveSongFromWatchlistParams struct {
	SongID string `json:"song_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RemoveSongFromWatchlist(ctx context.Context, arg RemoveSongFromWatchlistParams) error {
	_, err := q.exec(ctx, q.removeSongFromWatchlistStmt, removeSongFromWatchlist, arg.SongID, arg.UserID)
	return err
}

const watchSong = `-- name: WatchSong :one
INSERT INTO watchlists (user_id, song_id) VALUES (?, ?) RETURNING user_id, song_id
`

type WatchSongParams struct {
	UserID string `json:"user_id"`
	SongID string `json:"song_id"`
}

func (q *Queries) WatchSong(ctx context.Context, arg WatchSongParams) (Watchlist, error) {
	row := q.queryRow(ctx, q.watchSongStmt, watchSong, arg.UserID, arg.SongID)
	var i Watchlist
	err := row.Scan(&i.UserID, &i.SongID)
	return i, err
}
